version: '3.8'

services:
  deepseek-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: deepseek-api:arm64
    container_name: deepseek-api
    platform: linux/arm64
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./backend/appsettings.json:/app/appsettings.json:ro
    networks:
      - deepseek-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  deepseek-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: deepseek-frontend:arm64
    container_name: deepseek-frontend
    platform: linux/arm64
    ports:
      - "4200:80"
    depends_on:
      - deepseek-api
    networks:
      - deepseek-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  deepseek-network:
    driver: bridge

volumes:
  api-data: 