version: '3.8'

services:
  deepseek-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: deepseek-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # DeepSeek API Configuration
      - DeepSeek__ModelId=deepseek-chat
      - DeepSeek__ApiKey=sk-4de054d548984d8b97b5f5e7d630b6a2
      - DeepSeek__Endpoint=https://api.deepseek.com/v1/
      - DeepSeek__ServiceId=deepseek
      # Local Model Configuration (points to Ollama service)
      - DeepSeek__LocalModelEndpoint=http://ollama:11434/v1/
      - DeepSeek__LocalModelId=deepseek-r1:latest
      - DeepSeek__LocalServiceId=local-deepseek
    volumes:
      - ./backend/appsettings.json:/app/appsettings.json:ro
    networks:
      - deepseek-network
    restart: unless-stopped
    depends_on:
      - ollama

  deepseek-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: deepseek-frontend
    ports:
      - "4200:80"
    depends_on:
      - deepseek-api
    networks:
      - deepseek-network
    restart: unless-stopped

  # Optional: Ollama service for local model support
  # Remove or comment out if you don't want local model support
  ollama:
    image: ollama/ollama:latest
    container_name: deepseek-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - deepseek-network
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Uncomment the following lines if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  deepseek-network:
    driver: bridge

volumes:
  api-data:
  ollama-data: 